# Generated by Django 5.1.5 on 2025-02-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
